image: Visual Studio 2017

environment:
  CMAKE_ARGS: '-G "NMake Makefiles JOM" -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo'
  matrix:
  - QTDIR: C:\Qt\5.9\msvc2017 # Oldest supported Qt, 32-bit
    VCVARS: "vcvars32.bat"
    PLATFORM: x86
  - QTDIR: C:\Qt\5.13\msvc2017 # Fresh Qt, 32-bit
    VCVARS: "vcvars32.bat"
    PLATFORM: x86
  - QTDIR: C:\Qt\5.13\msvc2017_64 # Fresh Qt, 64-bit
    VCVARS: "vcvars64.bat"
    PLATFORM:

init:
- call "%QTDIR%\bin\qtenv2.bat"
- set PATH=C:\Qt\Tools\QtCreator\bin;%PATH%
- call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\%VCVARS%" %PLATFORM%
- cd /D "%APPVEYOR_BUILD_FOLDER%"

before_build:
- git submodule update --init --recursive

build_script:
- cmake %CMAKE_ARGS% -H. -Bbuild
- cmake --build build

#after_build:
#- cmake --build build --target install
#- 7z a quotient.zip "%DEPLOY_DIR%\"

# Uncomment this to connect to the AppVeyor build worker
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

test: off

#artifacts:
#- path: quotient.zip
